### ISSUE TITLE
NPM package v1.1.0 is missing the lib folder

### ISSUE THREAD

**Issue by KishCom** [StefanIndustries/node-asuswrt#7]
[Version 1.1.0 uploaded to NPM contains only 3 files](https://www.npmjs.com/package/node-asuswrt?activeTab=code): `LICENSE`, `README.md`, and `package.json` -- there is no lib folder or other source code.

Trying to use it will throw an `ERR_MODULE_NOT_FOUND`.

**Comment by StefanIndustries** [comment]
Resolved in 1.1.1. sorry :(
